name: Cargo Leptos and Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Install Rust and cargo-leptos
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Install cargo-leptos
        run: |
          cargo install cargo-leptos
          rustup target add wasm32-unknown-unknown  
      
      # Step 3: Build and serve with cargo-leptos in the specific directory
      - name: Run Cargo Leptos Serve
        run: |
          cd examples/leptos-test
          cargo leptos serve
        shell: bash

      # Step 4: Wait for the server to start (adjust sleep as necessary)
      - name: Wait for Leptos server
        run: sleep 10

      # Step 5: Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 6: Install Node.js dependencies for Playwright
      - name: Install npm dependencies
        run: npm ci

      # Step 7: Run Playwright tests in a specific directory
      - name: Run Playwright Tests
        run: |
          cd examples/leptos-test/end2end
          npx playwright test

      # Optionally, upload test artifacts (like reports)
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: playwright-report
          path: examples/leptos-test/end2end/test-results/.last-run.json
