name: Cargo Leptos and Playwright Tests

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Use binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-leptos
        run: |
          cargo binstall cargo-leptos -y
          rustup target add wasm32-unknown-unknown  

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: examples/leptos-test/end2end/package-lock.json
        
      - name: Install npm dependencies and playwright
        working-directory: examples/leptos-test/end2end
        run: |
          npm ci
          npx playwright install --with-deps
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build example
        working-directory: examples/leptos-test
        run: cargo leptos build --release
      
      - name: Run server in background
        working-directory: target/release
        run: ./leptos-test &

      - name: Run playwright tests
        working-directory: examples/leptos-test/end2end
        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: examples/leptos-test/end2end/test-results/last-run.json
