name: Cargo Leptos and Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Install cargo-leptos
        run: |
          cargo install cargo-leptos
          rustup target add wasm32-unknown-unknown  

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        working-directory: examples/leptos-test/end2end
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: examples/leptos-test/end2end
        run: npx playwright install

      - name: Run Playwright Tests
        working-directory: examples/leptos-test
        run: |
          cargo leptos end-to-end
          cd end2end
          npx playwright test

      - name: Upload Playwright Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: examples/leptos-test/end2end/test-results/.last-run.json
